[package]
name = "jmod"
version = "0.1.0"
authors = ["chris.henderson <chris.henderson@alation.com>"]
edition = "2018"

[dependencies]
carmen = "0.1.0"
structopt = "0.2.15"
tempdir = "0.3.7"
lib = { path = "lib" }